### ISSUE TITLE
Bluetooth Packet Handling Issue on Android 14 - Flutter

### ISSUE THREAD

**Issue by david2701** [google/android-auto-companion-android#6] opened 2024-01-26 10:50 UTC
Hello, 

I am writing to report a recurring issue observed in the Bluetooth communication handling of our application after updating to Android 14. The application is experiencing unexpected behavior when receiving Bluetooth packets, which was not present in Android 13. Below is the log output that captures the essence of the problem:
<img width="852" alt="Capture d’écran 2024-01-25 à 13 22 53" src="https://github.com/google/android-auto-companion-android/assets/6515966/288b744f-eef6-4d79-bd87-104bdf3cbbb3">

W/PacketPayloadStream ( 2804): Received a first message that is not the start of a packet. Ignoring.
I/BluetoothGattManager( 2804): Received data from service 5e2a68a4-27be-43f9-8d1e-4546976fabd7
I/BluetoothMessageStreamV2( 2804): Received packet 9 of 9 for message 269 containing 90 bytes.

The warning `W/PacketPayloadStream ( 2804): Received a first message that is not the start of a packet. Ignoring.` suggests that there is a discrepancy in how packet starts are being identified in the Bluetooth data stream.

This issue is consistently reproducible on devices that have been updated to Android 14. The same application running on Android 13 does not exhibit this problem, indicating that there has been a change in the Bluetooth stack or relevant system handling that is causing these messages to be misinterpreted or mishandled.

I would greatly appreciate any guidance or acknowledgment of this issue. If there are any workarounds or insights into the nature of these changes in Android 14's Bluetooth handling, it would be beneficial for our development team to know.

Thank you for your attention to this matter.

**Comment by david2701** [comment] 2024-02-05 23:49
@yaoyx108, It would be possible to see the situation, Thanks

**Comment by yaoyx108** [comment] 2024-02-06 22:56
Hi,

Thanks for raising the issue. 

Without knowing more detail, I can't tell what the cause is. Please work with your Google Automotive Services (GAS) partner to file a bug report. 

Specifically, in the bug please provide your IHU Android build, phone build, IHU companion SDK version, and Android companion SDK version.

Thanks.

**Comment by its-rohith** [comment] 2024-02-14 15:28
Hello @david2701 , 

Faced the same issue and able to fix the same after adding and enabling the below permissions in the Application. 
Also need to use the latest version of the library which is 3.2.1

BLUETOOTH_CONNECT, BLUETOOTH_SCAN , ACCESS_FINE_LOCATION , ACCESS_BACKGROUND_LOCATION , BLUETOOTH_ADMIN , BLUETOOTH , BLUETOOTH_ADVERTISE , ACCESS_NOTIFICATION_POLICY

**Comment by yaoyx108** [comment] 2024-02-20 22:02
@its-rohith these permissions are required to start the connection, but given the logs @david2701 shared, they were able to receive messages (past the permission issue). Just that the messages weren't as expected.

(We will soon update the reference app, including the manifest, to handle the permissions. In the mean time, you'll indeed to grant these permissions manually.)

It could be caused by various factors, so I'd like to understand more.

**Comment by david2701** [comment] 2024-02-20 22:10
Thank you for your responses. @yaoyx108 @its-rohith 

Unfortunate even with the inclusion of all these permissions, continued to receive the same problem in Android 14.

Tests performed on Pixel and Samsung Phones.

Already we created a log tracker on Google but to this day, we have no response.

The Situation is strange since the connection works smoothly, but the connection is temporarily lost and reconnected, situation that only occurs on Android 14, Android 13 & IOS functions perfectly.

**Comment by yaoyx108** [comment] 2024-02-20 23:31
@david2701 Could you please link the issue you opened on Google Issue Tracker? Thank you.

**Comment by david2701** [comment] 2024-02-21 09:48
@yaoyx108 https://partnerissuetracker.corp.google.com/issues/324215155

**Comment by yaoyx108** [comment] 2024-04-18 18:21
Hi @david2701 the issue has been closed. I'll close this one. 

FWIW, in general please work with the android partner engineers to raise issues.

**Closed as completed by yaoyx108** 2024-04-18 18:21 UTC
